name: flutter_projects
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.1.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  meta: ^1.12.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
